### ISSUE TITLE
LyraPhase/sprout-wrap macOS Monterey + M1 Apple Silicon Support

### ISSUE THREAD

**Issue by trinitronx** [LyraPhase/sprout-wrap#205]
- [x] Transfer trinitronx/sprout-wrap repo into LyraPhase Org
- [x] macOS Big Sur Support + tested on bare metal hardware
  - [x] Laptop Setup - Fixed Vagrant VM for local testing setup + teardown ✅
- [x] macOS Monterey
  - [x] Laptop Setup - Vagrant VM for local testing setup + teardown ✅
- [x] Apple Silicon support (`arm64`) ✅
  - [x] Patch [sous-chefs/homebrew][1] cookbook (sous-chefs/homebrew#154 Merged! ✅)
- [x] Port `sprout-wrap` to GitHub Actions
  - [x] Ran into flaky networking issue on job runner nodes… (actions/virtual-environments#4809) Fixed! ✅
  - [x] Workaround for slow `brew update` commands (LyraPhase/sprout-wrap#57
- [x] Update README for 2021 + LyraPhase Org (LyraPhase/sprout-wrap/58) ✅
- [ ] Modern Chef support (16.x, 17.x)
  - [ ] Update soloist gem (in-progress)
    - [x] Update & unpin gemspec dependencies for Chef 17 ✅
    - [x] RSpec tests passing ✅
    - [x] Created basic CI smoketest, also passing ✅
    - [x] Port from TravisCI to GitHub Actions ✅
    - [x] PR Merged to `develop` branch in my fork: trinitronx/soloist#1
    - [ ] Reach out to @mkocher about [`soloist` gem][2] updates
      - [ ] If that fails... try RubyGems new Gem Adoption / Ownership Request path
      - [ ] Or: fork & use GitHub source in `Gemfile`
  - [ ] macOS Monterey VM testing
    - [ ] QEMU / libvirt stack: [Check status of PRs & dependencies][3]
      - [ ] [`ruby-libvirt`](https://gitlab.com/libvirt/libvirt-ruby/-/merge_requests/19)
        - [x] Merged to `master` branch! 🎉
        - [ ] Needs official release to RubyGems
          - [x] Reached out to repo maintainers in [`libvirt/libvirt-ruby#4` (GitLab)][4]
          - [x] Pinged RubyGems maintainer (@clalancette) in [`clalancette/myrosdistro#8`][5]
          - [ ] If this fails, then perhaps try to initiate [Rubygems.org Adoption][6] process ?
      - [ ] Get QEMU + `libvirtd` stack working on new CI system install
        - [x] Bare-bones vanilla QEMU + `libvirtd` to launch VM
        - [ ] `vagrant` + `vagrant-libvirt` stack local launch (for testing / PoC)
        - [ ] Remote macOS workstation `vagrant` + `vagrant-libvirt` stack to launch VM over SSH remotely (on CI system host)

[1]: https://github.com/sous-chefs/homebrew
[2]: https://github.com/mkocher/soloist
[3]: https://github.com/vagrant-libvirt/vagrant-libvirt/issues/1205
[4]: https://gitlab.com/libvirt/libvirt-ruby/-/issues/4
[5]: https://github.com/clalancette/myrosdistro/issues/8
[6]: https://blog.rubygems.org/2022/01/19/rubygems-adoptions.html
